spring:
  application:
    name: ms-patientNotes
  data:
    mongodb:
      uri: mongodb://admin_note:1234@localhost:27027/db_patientNote
  cloud:
    discovery:
      enabled: true
server:
  port: 9565
logging:
  level:
    org:
      springframework:
        cloud:
          config: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9502/eureka
symptoms:
  fume: fume(ur|use|r)?
  hemoglobine: hémoglobine a1c
  microalbumine: microalbumine
  taille: taille
  poids: poids(?!\s+(égal ou inférieur|recommandé))
  anormal: anormal
  cholesterol: cholestérol
  vertige: vertige(s)?
  rechute: rechute
  reaction: réaction
  anticorps: anticorps
